version: "3.8"

volumes:
  pgdata: {}

services:
  app :
    build: ./app/
    volumes:
      - .:/app:z
  db:
    build: ./database/
    restart: always
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/postgresql/data/